### ISSUE TITLE
Handle trailing and leading slashes in config values

### ISSUE THREAD

**Issue by ericlarssen-wf** [njoyce/flask-assetrev#1]
Adding a path such as `/assets` to `ASSETREV_BASE_PATH` will result in a path of `/static//assets`.

**Comment by WilliamMayor** [comment]
Similarly to this, my manifest.json file contains absolute URLs, and this caused paths to contain `/static//xys.js`.

I got round this by setting the ASSETREV_BASE_URL to not have a trailing slash. This means I have to hardcode my base URL for each environment (but that's not too arduous).

**Comment by ericlarssen-wf** [comment]
😦
